version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

build:
  project: JustObjectsPrototype.Universal\JustObjectsPrototype.Universal.sln

before_build:
  JustObjectsPrototype.Universal\.nuget\nuget.exe restore JustObjectsPrototype.Universal\JustObjectsPrototype.Universal.sln

after_test:
  - ps: .\JustObjectsPrototype.Universal\.nuget\pack.ps1

artifacts:
  - path: JustObjectsPrototype.Universal\JustObjectsPrototype.Universal\bin\Debug\JustObjectsPrototype.Universal.dll
    name: JustObjectsPrototype.Universal.dll
  - path: '**\JOP.universal*.nupkg'
    name: JOP.universal.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: mYNxybjJqKR3bOn+cYo6o7SPvlgOApzwnI7rep4TCYjTjYgb7T1fG28lFrgcX2Jk
  artifact: JOP.universal.nupkg
  